-- Transaction-only fixtures. No real users, files or notifications are committed.
begin;
do $test$
declare ids uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];e uuid:=gen_random_uuid();quick uuid:=gen_random_uuid();benefit uuid:=gen_random_uuid();thread uuid;v jsonb;n integer;i integer;
begin
 for i in 1..7 loop
  insert into auth.users(id,aud,role,email,email_confirmed_at,is_anonymous,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values(ids[i],'authenticated','authenticated','svoya-test-'||ids[i]||'@example.invalid',now(),false,'{}','{}',now(),now());
  insert into storage.objects(bucket_id,name,owner_id) values('svoya-profile-photos',ids[i]::text||'/fixture.webp',ids[i]::text);
  insert into public.svoya_profiles(id,name,city,photo_paths,membership_status,discoverable,welcomes_newcomers) values(ids[i],'Тестова учасниця','Тестове місто',array[ids[i]::text||'/fixture.webp'],case when i=2 then 'pending' else 'approved' end,true,true);
 end loop;
 insert into public.svoya_admins(user_id) values(ids[7]);
 insert into public.svoya_entries(id,owner_id,kind,title,city,starts_at,ends_at,capacity) values(e,ids[1],'event','Тестова зустріч','Тестове місто',now()+interval '50 minutes',now()+interval '110 minutes',2);
 insert into public.svoya_benefits(id,owner_id,title,provider,description,terms,city,valid_until,status) values(benefit,ids[1],'Тестова пропозиція','Тестовий партнер','Тест умов без публікації','Умови для тесту','Тестове місто',now()+interval '1 day','published');
 insert into public.svoya_benefit_codes(benefit_id,code) values(benefit,'FIXTURE-CODE');
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[2],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[2]::text,true);execute 'set local role authenticated';
begin insert into public.svoya_entries(owner_id,kind,title,city,starts_at) values(ids[2],'event','Заборонена подія','Тестове місто',now()+interval '1 day');raise exception 'TEST_PENDING_PUBLISH_ALLOWED';exception when insufficient_privilege then null;end;
begin perform public.svoya_community_action('join',jsonb_build_object('entry_id',e));raise exception 'TEST_PENDING_JOIN_ALLOWED';exception when others then if sqlerrm<>'SV_REVIEW_PENDING' then raise;end if;end;
begin update public.svoya_profiles set membership_status='approved' where id=ids[2];raise exception 'TEST_SELF_APPROVAL_ALLOWED';exception when insufficient_privilege then null;end;
begin perform public.svoya_community_action('review_profile',jsonb_build_object('id',ids[2],'status','approved'));raise exception 'TEST_SELF_MODERATION_ALLOWED';exception when others then if sqlerrm<>'SV_ADMIN_ONLY' then raise;end if;end;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[3]::text,true);execute 'set local role authenticated';
v:=public.svoya_community_action('join',jsonb_build_object('entry_id',e,'needs_greeter',true));if v->>'status'<>'pending' then raise exception 'TEST_JOIN_STATUS';end if;
if not exists(select 1 from public.svoya_memberships where entry_id=e and user_id=ids[3] and needs_greeter and greeter_id=ids[1]) then raise exception 'TEST_GREETER';end if;
begin perform public.svoya_community_action('join',jsonb_build_object('entry_id',e));raise exception 'TEST_DUPLICATE_JOIN';exception when others then if sqlerrm<>'SV_ALREADY_JOINED' then raise;end if;end;
if exists(select 1 from public.svoya_benefit_codes where benefit_id=benefit) then raise exception 'TEST_PRIVATE_CODE_LEAK';end if;
v:=public.svoya_community_action('claim_benefit',jsonb_build_object('id',benefit));if v->>'code'<>'FIXTURE-CODE' then raise exception 'TEST_CLAIM_CODE';end if;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[4],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[4]::text,true);execute 'set local role authenticated';
v:=public.svoya_community_action('join',jsonb_build_object('entry_id',e));if v->>'status'<>'pending' then raise exception 'TEST_SECOND_SEAT';end if;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[5],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[5]::text,true);execute 'set local role authenticated';
v:=public.svoya_community_action('join',jsonb_build_object('entry_id',e));if v->>'status'<>'waitlisted' then raise exception 'TEST_WAITLIST';end if;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[1]::text,true);execute 'set local role authenticated';
update public.svoya_memberships set status='joined' where entry_id=e and user_id in (ids[3],ids[4]);
begin update public.svoya_memberships set status='joined' where entry_id=e and user_id=ids[5];raise exception 'TEST_OVERBOOK_ALLOWED';exception when others then if sqlerrm<>'SV_FULL' then raise;end if;end;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[3]::text,true);execute 'set local role authenticated';
delete from public.svoya_memberships where entry_id=e and user_id=ids[3];
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[5],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[5]::text,true);execute 'set local role authenticated';
if not exists(select 1 from public.svoya_memberships where entry_id=e and user_id=ids[5] and status='pending') then raise exception 'TEST_WAITLIST_NOT_PROMOTED';end if;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[6],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[6]::text,true);execute 'set local role authenticated';
update public.svoya_memberships set status='joined' where entry_id=e and user_id=ids[5];get diagnostics n=row_count;if n<>0 then raise exception 'TEST_OUTSIDER_APPROVAL';end if;
begin insert into public.svoya_messages(entry_id,user_id,body) values(e,ids[6],'Недозволений чат');raise exception 'TEST_OUTSIDER_CHAT';exception when insufficient_privilege then null;end;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[1]::text,true);execute 'set local role authenticated';
update public.svoya_memberships set status='joined' where entry_id=e and user_id=ids[5];
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[4],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[4]::text,true);execute 'set local role authenticated';
insert into public.svoya_reminders(user_id,entry_id,minutes_before) values(ids[4],e,60);
insert into public.svoya_messages(entry_id,user_id,body) values(e,ids[4],'Дозволений чат');
v:=public.svoya_community_action('friend_invite',jsonb_build_object('user_id',ids[5]));thread:=(v->>'id')::uuid;
begin insert into public.svoya_friend_messages(friendship_id,user_id,body) values(thread,ids[4],'До згоди');raise exception 'TEST_CHAT_BEFORE_CONSENT';exception when insufficient_privilege then null;end;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[5],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[5]::text,true);execute 'set local role authenticated';
perform public.svoya_community_action('friend_respond',jsonb_build_object('id',thread,'status','accepted'));insert into public.svoya_friend_messages(friendship_id,user_id,body) values(thread,ids[5],'Після згоди');
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[4],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[4]::text,true);execute 'set local role authenticated';
if not exists(select 1 from public.svoya_friend_messages where friendship_id=thread) then raise exception 'TEST_ACCEPTED_CHAT_UNREADABLE';end if;insert into public.svoya_blocks(blocker_id,blocked_id) values(ids[4],ids[5]);if exists(select 1 from public.svoya_profiles where id=ids[5]) or exists(select 1 from public.svoya_friendships where id=thread) or exists(select 1 from public.svoya_friend_messages where friendship_id=thread) then raise exception 'TEST_BLOCK_LEAK';end if;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[5],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[5]::text,true);execute 'set local role authenticated';
if exists(select 1 from public.svoya_profiles where id=ids[4]) then raise exception 'TEST_REVERSE_BLOCK_LEAK';end if;
begin insert into public.svoya_friend_messages(friendship_id,user_id,body) values(thread,ids[5],'Після блокування');raise exception 'TEST_CHAT_AFTER_BLOCK';exception when insufficient_privilege then null;end;
execute 'reset role';perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[7],'role','authenticated','is_anonymous',false)::text,true);perform set_config('request.jwt.claim.sub',ids[7]::text,true);execute 'set local role authenticated';
perform public.svoya_community_action('review_profile',jsonb_build_object('id',ids[2],'status','approved','note','Тестова перевірка'));if not exists(select 1 from public.svoya_profiles where id=ids[2] and membership_status='approved') then raise exception 'TEST_ADMIN_REVIEW';end if;
execute 'reset role';perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{}',true);
perform svoya_private.send_reminders();perform svoya_private.send_reminders();
select count(*) into n from public.svoya_notifications where user_id=ids[4] and entry_id=e and kind='reminder';if n<>1 then raise exception 'TEST_REMINDER_NOT_IDEMPOTENT';end if;
select count(*) into n from public.svoya_notifications where user_id=ids[5] and entry_id=e and kind='reminder';if n<>0 then raise exception 'TEST_REMINDER_WITHOUT_OPTIN';end if;
insert into public.svoya_entries(id,owner_id,kind,title,city,starts_at,ends_at,expires_at,format) values(quick,ids[1],'event','Швидкий тестовий план','Тестове місто',now()+interval '1 hour',now()+interval '2 hours',now()+interval '2 hours','quick');
update public.svoya_entries set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour',expires_at=now()-interval '1 hour' where id=quick;
execute 'set local role anon';
if exists(select 1 from public.svoya_entries where id=quick) then raise exception 'TEST_EXPIRED_QUICK_VISIBLE';end if;
begin perform public.svoya_community_action('claim_benefit',jsonb_build_object('id',benefit));raise exception 'TEST_ANON_RPC_ACCESS';exception when insufficient_privilege then null;end;
execute 'reset role';
end $test$;
rollback;
select 'PASS: moderation, RLS, block both ways, mutual chat, capacity, waitlist, newcomer, private benefits, opt-in/idempotent reminders, expiry; all fixtures rolled back' as result;

